// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njngeinlpkkgeylmgvla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qbmdlaW5scGtrZ2V5bG1ndmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTg2NDcsImV4cCI6MjA3MDIzNDY0N30.UsC3nT5d8HC4itzUp9ppSco1vzqOpGkvfBWfExERbGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});